// الحصول على جميع روابط القائمة
const navLinks = document.querySelectorAll('#home .navbar nav ul li a');

// دالة لتحديد الصفحة الحالية
function setActiveLink() {
  navLinks.forEach(link => {
    if (link.href === window.location.href) {
      link.classList.add('active');
    } else {
      link.classList.remove('active');
    }
  });
}

// استدعاء الدالة عند تحميل الصفحة وعند تغيير عنوان URL
window.addEventListener('DOMContentLoaded', setActiveLink);
window.addEventListener('hashchange', setActiveLink);
/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/PRrYLujugUrIyoGX/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group name="Group 2" position={[3.3, -134.5, 308.67]} scale={[0.99, 0.99, 1.47]}>
            <mesh
              name="Text"
              geometry={nodes.Text.geometry}
              material={materials['Text Material']}
              castShadow
              receiveShadow
              position={[-0.15, -1.21, 0.5]}
            />
            <mesh
              name="Botón"
              geometry={nodes.Botón.geometry}
              material={materials['Botón Material']}
              castShadow
              receiveShadow
              position={[0, 0, -0.5]}
            />
          </group>
          <group name="REACCIONES" position={[-161.46, 804.65, 307.13]}>
            <mesh
              name="NORMAL"
              geometry={nodes.NORMAL.geometry}
              material={materials['NORMAL Material']}
              castShadow
              receiveShadow
              position={[0, -55.32, 0]}
            />
            <mesh
              name="NORMAL1"
              geometry={nodes.NORMAL1.geometry}
              material={materials['NORMAL1 Material']}
              castShadow
              receiveShadow
              position={[0, -1446.91, 0]}
            />
          </group>
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
            position={[0, 0, -964.77]}
          />
          <group name="Cuerpo">
            <group name="MANOS" position={[1, -84.34, 96]}>
              <mesh
                name="DER"
                geometry={nodes.DER.geometry}
                material={materials['DER Material']}
                castShadow
                receiveShadow
                position={[-105, -5.03, 0]}
              />
              <mesh
                name="IZ"
                geometry={nodes.IZ.geometry}
                material={materials['IZ Material']}
                castShadow
                receiveShadow
                position={[105, 5.03, 0]}
              />
            </group>
            <group name="Robot" position={[-0.92, 24.22, -25.13]}>
              <group name="Cuerpo1" position={[1.68, 0, -9.76]} scale={1.03}>
                <mesh
                  name="CUELLO"
                  geometry={nodes.CUELLO.geometry}
                  material={materials['CUELLO Material']}
                  castShadow
                  receiveShadow
                  position={[-0.22, -40.8, -13.35]}
                  scale={0.97}
                />
                <mesh
                  name="CABEZA"
                  geometry={nodes.CABEZA.geometry}
                  material={materials['CABEZA Material']}
                  castShadow
                  receiveShadow
                  position={[0, 12.32, 0]}
                />
              </group>
              <group name="Compornentes" position={[0, 0, 7.82]} scale={1.03}>
                <mesh
                  name="OREJA DER"
                  geometry={nodes['OREJA DER'].geometry}
                  material={materials['OREJA DER Material']}
                  castShadow
                  receiveShadow
                  position={[-89.8, 0, -14.63]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={0.39}
                />
                <mesh
                  name="OREJA IZ"
                  geometry={nodes['OREJA IZ'].geometry}
                  material={materials['OREJA IZ Material']}
                  castShadow
                  receiveShadow
                  position={[89.8, 0, -14.63]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={0.39}
                />
                <group name="ESTADO" position={[1.64, 7.58, 26.55]}>
                  <mesh
                    name="feliz 3"
                    geometry={nodes['feliz 3'].geometry}
                    material={materials['feliz 3 Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={0.73}
                  />
                  <mesh
                    name="NORMAL2"
                    geometry={nodes.NORMAL2.geometry}
                    material={materials['NORMAL2 Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={0.73}
                  />
                  <mesh
                    name="corazón 3"
                    geometry={nodes['corazón 3'].geometry}
                    material={materials['corazón 3 Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={0.73}
                  />
                  <mesh
                    name="feliz 2"
                    geometry={nodes['feliz 2'].geometry}
                    material={materials['feliz 2 Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    scale={0.73}
                  />
                </group>
              </group>
            </group>
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[200, 300, 300]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
